export const files = [
  "IM_PHD_3.csv",
  "IM_PHD_4.csv",
  "IM_PHD_5.csv",
  "IM_PHD_6.csv",
  "IM_PHD_7.csv",
  "IM_PHD_8.csv",
  "IM_PHD_9.csv",
  "IM_PNC_3.csv",
  "IM_PNC_4.csv",
  "IM_PNC_5.csv",
  "IM_PNC_6.csv",
  "IM_PNC_7.csv",
  "IM_PNC_8.csv",
  "IM_PNC_9.csv",
  "IM_PRS_3.csv",
  "IM_PRS_4.csv",
  "IM_PRS_5.csv",
  "IM_PRS_6.csv",
  "IM_PRS_7.csv",
  "IM_PRS_8.csv",
  "IM_PRS_9.csv",
  "IM_S_N_3.csv",
  "IM_S_N_4.csv",
  "IM_S_N_5.csv",
  "IM_S_N_6.csv",
  "IM_S_N_7.csv",
  "IM_S_N_8.csv",
  "IM_S_N_9.csv",
]

export const colors = {
  red: "#FF8B8B",
  green: "#A4DCD0",
  lightGreen: "#E7FFFA",
  darkGreen: "#5f7772",
  accent: '#FF8B8B',
} as const
